### ISSUE TITLE
集群模式下Node节点到的是容器内部IP，导致主节点无法访问到

### ISSUE THREAD

**Issue by Jesn** [dotnetcore/AgileConfig#137]
```
 agile_config_node2:
    image: "kklldog/agile_config"
    ports:
      - "15002:5000"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - cluster=true
      - db__provider=mysql
      - db__conn= database=configcenter;data source=192.168.0.115;User Id=root;password=mdsd;port=3306
 ```

没有指定节点IP的地方，导致获取到的是容器内部的IP，导致节点离线

<img width="1103" alt="image" src="https://github.com/dotnetcore/AgileConfig/assets/5728274/2d00f39b-ff3e-4ecf-9782-397dbba4d15c" />
